name: Update Database

on:
  workflow_dispatch:
    inputs:
      base64content:
        description: 'Base64 content of database.db'
        required: true
      message:
        description: 'Commit message'
        required: true

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Decode and write file
        run: |
          echo "${{ github.event.inputs.base64content }}" | base64 -d > database.db

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add database.db
          git commit -m "${{ github.event.inputs.message }}"
          git push
